export type Stage = 'Foundation' | 'Ecosystem' | 'Advanced';
export type Category = 'Layer 1' | 'Layer 2' | 'DeFi' | 'Payments' | 'NFT/Gaming' | 'Infrastructure' | 'Privacy' | 'Meme';

export interface Coin {
  symbol: string;
  name: string;
  category: Category;
  stage: Stage;
  description: string;
  geckoId: string;
  logoUrl: string;
}

const GECKO = 'https://assets.coingecko.com/coins/images';

export const COINS: Coin[] = [
  // ─── FOUNDATION ────────────────────────────────────────────────────────────
  { symbol: 'BTC',   name: 'Bitcoin',            category: 'Layer 1',       stage: 'Foundation', description: 'The original cryptocurrency — digital gold and peer-to-peer payments.',               geckoId: 'bitcoin',                     logoUrl: `${GECKO}/1/small/bitcoin.png` },
  { symbol: 'ETH',   name: 'Ethereum',           category: 'Layer 1',       stage: 'Foundation', description: 'The programmable blockchain powering DeFi, NFTs, and smart contracts.',              geckoId: 'ethereum',                    logoUrl: `${GECKO}/279/small/ethereum.png` },
  { symbol: 'SOL',   name: 'Solana',             category: 'Layer 1',       stage: 'Foundation', description: 'High-throughput, low-cost Layer 1 — 65,000 TPS with sub-second finality.',           geckoId: 'solana',                      logoUrl: `${GECKO}/4128/small/solana.png` },
  { symbol: 'BNB',   name: 'BNB',                category: 'Layer 1',       stage: 'Foundation', description: 'Native token of BNB Chain and the Binance exchange ecosystem.',                       geckoId: 'binancecoin',                 logoUrl: `${GECKO}/825/small/bnb-icon2_2x.png` },
  { symbol: 'XRP',   name: 'XRP',                category: 'Payments',      stage: 'Foundation', description: 'Cross-border bank settlement — moves money in 3–5 seconds at near-zero cost.',        geckoId: 'ripple',                      logoUrl: `${GECKO}/44/small/xrp-symbol-white-128.png` },
  { symbol: 'LTC',   name: 'Litecoin',           category: 'Payments',      stage: 'Foundation', description: 'Bitcoin fork optimised for fast, lightweight everyday transactions.',                  geckoId: 'litecoin',                    logoUrl: `${GECKO}/2/small/litecoin.png` },
  { symbol: 'XLM',   name: 'Stellar',            category: 'Payments',      stage: 'Foundation', description: 'Open financial network for micropayments and global financial access.',               geckoId: 'stellar',                     logoUrl: `${GECKO}/100/small/Stellar_symbol_black_RGB.png` },
  { symbol: 'ADA',   name: 'Cardano',            category: 'Layer 1',       stage: 'Foundation', description: 'Research-driven, peer-reviewed proof-of-stake blockchain platform.',                  geckoId: 'cardano',                     logoUrl: `${GECKO}/975/small/cardano.png` },
  { symbol: 'AVAX',  name: 'Avalanche',          category: 'Layer 1',       stage: 'Foundation', description: 'Sub-second finality with customisable subnet architecture.',                          geckoId: 'avalanche-2',                 logoUrl: `${GECKO}/12559/small/Avalanche_Circle_RedWhite_Trans.png` },
  { symbol: 'DOGE',  name: 'Dogecoin',           category: 'Meme',          stage: 'Foundation', description: 'The original meme coin — now a legitimate payments network backed by Elon Musk.',     geckoId: 'dogecoin',                    logoUrl: `${GECKO}/5/small/dogecoin.png` },
  { symbol: 'SHIB',  name: 'Shiba Inu',          category: 'Meme',          stage: 'Foundation', description: 'Dogecoin killer turned DeFi ecosystem — ShibaSwap, Shibarium L2, and BONE.',         geckoId: 'shiba-inu',                   logoUrl: `${GECKO}/11939/small/shiba.png` },
  { symbol: 'PEPE',  name: 'Pepe',               category: 'Meme',          stage: 'Foundation', description: 'Pepe the Frog transformed into crypto\'s cultural mascot — $10B+ market cap meme coin.', geckoId: 'pepe',                        logoUrl: `${GECKO}/29850/small/pepe-token.jpeg` },
  { symbol: 'BCH',   name: 'Bitcoin Cash',       category: 'Payments',      stage: 'Foundation', description: 'Bitcoin hard fork focused on fast, cheap on-chain payments at scale.',                geckoId: 'bitcoin-cash',                logoUrl: `${GECKO}/780/small/bitcoin-cash-circle-grayscale.png` },

  // ─── ECOSYSTEM ─────────────────────────────────────────────────────────────
  { symbol: 'NEAR',  name: 'NEAR Protocol',      category: 'Layer 1',       stage: 'Ecosystem',  description: 'Developer-friendly L1 with sharding and a human-readable account system.',           geckoId: 'near',                        logoUrl: `${GECKO}/10365/small/near_icon.png` },
  { symbol: 'TON',   name: 'Toncoin',            category: 'Layer 1',       stage: 'Ecosystem',  description: 'Telegram-native blockchain — 900M users, instant transactions, TON Space.',          geckoId: 'the-open-network',            logoUrl: `${GECKO}/17980/small/ton_symbol.png` },
  { symbol: 'TRX',   name: 'TRON',               category: 'Layer 1',       stage: 'Ecosystem',  description: 'High-volume entertainment and stablecoin payment network — largest USDT chain.',      geckoId: 'tron',                        logoUrl: `${GECKO}/1094/small/tron-logo.png` },
  { symbol: 'APT',   name: 'Aptos',              category: 'Layer 1',       stage: 'Ecosystem',  description: 'Move-language blockchain built by ex-Meta Diem engineers for safe, fast apps.',       geckoId: 'aptos',                       logoUrl: `${GECKO}/26455/small/aptos_round.png` },
  { symbol: 'SUI',   name: 'Sui',                category: 'Layer 1',       stage: 'Ecosystem',  description: 'Object-centric Move blockchain with parallel execution and instant settlement.',       geckoId: 'sui',                         logoUrl: `${GECKO}/26375/small/sui_asset.jpeg` },
  { symbol: 'HBAR',  name: 'Hedera',             category: 'Infrastructure', stage: 'Ecosystem', description: 'Enterprise-grade hashgraph — 10,000 TPS, carbon-negative, governed by Fortune 500s.', geckoId: 'hedera-hashgraph',             logoUrl: `${GECKO}/3688/small/HBAR.png` },
  { symbol: 'ALGO',  name: 'Algorand',           category: 'Payments',      stage: 'Ecosystem',  description: 'Pure proof-of-stake blockchain — 4-second finality, CBDCs, and green credentials.',   geckoId: 'algorand',                    logoUrl: `${GECKO}/4030/small/algorand.png` },
  { symbol: 'POL',   name: 'Polygon',            category: 'Layer 2',       stage: 'Ecosystem',  description: 'Ethereum scaling network and AggLayer hub for zero-knowledge chains.',                 geckoId: 'matic-network',               logoUrl: `${GECKO}/4713/small/matic-token-icon.png` },
  { symbol: 'ARB',   name: 'Arbitrum',           category: 'Layer 2',       stage: 'Ecosystem',  description: 'Leading Ethereum optimistic rollup — largest L2 by TVL and DeFi activity.',          geckoId: 'arbitrum',                    logoUrl: `${GECKO}/16547/small/photo_2023-03-29_21.47.00.jpeg` },
  { symbol: 'OP',    name: 'Optimism',           category: 'Layer 2',       stage: 'Ecosystem',  description: 'Superchain rollup ecosystem — Coinbase Base, Mode, and 30+ chains built on the OP Stack.', geckoId: 'optimism',                logoUrl: `${GECKO}/25244/small/Optimism.png` },
  { symbol: 'STRK',  name: 'Starknet',           category: 'Layer 2',       stage: 'Ecosystem',  description: 'ZK-rollup on Ethereum — Cairo language, recursive proofs, full EVM equivalence.',     geckoId: 'starknet',                    logoUrl: `${GECKO}/26433/small/starknet.png` },
  { symbol: 'LRC',   name: 'Loopring',           category: 'Layer 2',       stage: 'Ecosystem',  description: 'ZK-rollup DEX protocol on Ethereum — non-custodial trading at L1 security.',          geckoId: 'loopring',                    logoUrl: `${GECKO}/5779/small/loopring.png` },
  { symbol: 'UNI',   name: 'Uniswap',            category: 'DeFi',          stage: 'Ecosystem',  description: 'The original AMM DEX — $1T+ lifetime volume, v4 hooks, and Uniswap X intent protocol.', geckoId: 'uniswap',                  logoUrl: `${GECKO}/12504/small/uniswap-uni-logo.png` },
  { symbol: 'AAVE',  name: 'Aave',               category: 'DeFi',          stage: 'Ecosystem',  description: 'Largest decentralised lending protocol — flash loans, GHO stablecoin, $15B+ TVL.',    geckoId: 'aave',                        logoUrl: `${GECKO}/12645/small/AAVE.png` },
  { symbol: 'MKR',   name: 'MakerDAO',           category: 'DeFi',          stage: 'Ecosystem',  description: 'Governance token for the DAI stablecoin — oldest and most battle-tested DeFi protocol.', geckoId: 'maker',                    logoUrl: `${GECKO}/1364/small/Mark_Maker.png` },
  { symbol: 'CRV',   name: 'Curve Finance',      category: 'DeFi',          stage: 'Ecosystem',  description: 'Stablecoin AMM backbone of DeFi — underpins liquidity across every major protocol.',   geckoId: 'curve-dao-token',             logoUrl: `${GECKO}/12124/small/Curve.png` },
  { symbol: 'SUSHI', name: 'SushiSwap',          category: 'DeFi',          stage: 'Ecosystem',  description: 'Community-owned DEX on 20+ chains — lending, AMM, and cross-chain routing.',          geckoId: 'sushi',                       logoUrl: `${GECKO}/12271/small/512x512_Logo_no_chop.png` },
  { symbol: 'COMP',  name: 'Compound',           category: 'DeFi',          stage: 'Ecosystem',  description: 'Pioneer on-chain money market — algorithmic interest rates that defined DeFi lending.', geckoId: 'compound-governance-token',   logoUrl: `${GECKO}/10775/small/COMP.png` },
  { symbol: 'LINK',  name: 'Chainlink',          category: 'Infrastructure', stage: 'Ecosystem', description: 'Decentralised oracle network connecting smart contracts to real-world data.',           geckoId: 'chainlink',                   logoUrl: `${GECKO}/877/small/chainlink-new-logo.png` },
  { symbol: 'ENS',   name: 'Ethereum Name Service', category: 'Infrastructure', stage: 'Ecosystem', description: 'Decentralised naming for wallets, websites, and identity — yourname.eth.',        geckoId: 'ethereum-name-service',       logoUrl: `${GECKO}/18765/small/ens.jpg` },
  { symbol: 'IMX',   name: 'Immutable X',        category: 'NFT/Gaming',    stage: 'Ecosystem',  description: 'Zero-gas NFT Layer 2 — home to Gods Unchained, Guild of Guardians, and more.',        geckoId: 'immutable-x',                 logoUrl: `${GECKO}/17233/small/immutableX-icon.png` },
  { symbol: 'AXS',   name: 'Axie Infinity',      category: 'NFT/Gaming',    stage: 'Ecosystem',  description: 'Pioneer play-to-earn game — Ronin sidechain, 2M+ daily players at peak.',             geckoId: 'axie-infinity',               logoUrl: `${GECKO}/13029/small/axie_infinity_logo.png` },
  { symbol: 'SAND',  name: 'The Sandbox',        category: 'NFT/Gaming',    stage: 'Ecosystem',  description: 'Metaverse gaming platform — virtual land, user-created experiences, and brand partnerships.', geckoId: 'the-sandbox',            logoUrl: `${GECKO}/12129/small/sandbox_logo.jpg` },
  { symbol: 'MANA',  name: 'Decentraland',       category: 'NFT/Gaming',    stage: 'Ecosystem',  description: 'User-owned virtual world — LAND NFTs, wearables, and DAO-governed social spaces.',    geckoId: 'decentraland',                logoUrl: `${GECKO}/1990/small/decentraland-mana.png` },
  { symbol: 'GALA',  name: 'Gala Games',         category: 'NFT/Gaming',    stage: 'Ecosystem',  description: 'Web3 gaming ecosystem — 50+ games, player-owned items, and decentralised nodes.',      geckoId: 'gala',                        logoUrl: `${GECKO}/12493/small/GALA-COINGECKO.png` },
  { symbol: 'RON',   name: 'Ronin',              category: 'NFT/Gaming',    stage: 'Ecosystem',  description: 'Ethereum sidechain built for gaming — Axie Infinity, Pixels, and Mavis Hub.',         geckoId: 'ronin',                       logoUrl: `${GECKO}/28054/small/ronin.png` },

  // ─── ADVANCED ───────────────────────────────────────────────────────────────
  { symbol: 'DOT',   name: 'Polkadot',           category: 'Infrastructure', stage: 'Advanced',  description: 'Relay chain enabling multi-chain interoperability via parachains.',                   geckoId: 'polkadot',                    logoUrl: `${GECKO}/12171/small/polkadot.png` },
  { symbol: 'ATOM',  name: 'Cosmos',             category: 'Infrastructure', stage: 'Advanced',  description: 'Internet of Blockchains — IBC protocol connects 100+ sovereign chains.',             geckoId: 'cosmos',                      logoUrl: `${GECKO}/1481/small/cosmos_hub.png` },
  { symbol: 'GRT',   name: 'The Graph',          category: 'Infrastructure', stage: 'Advanced',  description: 'Decentralised indexing protocol — the Google of blockchain data.',                   geckoId: 'the-graph',                   logoUrl: `${GECKO}/13397/small/Graph_Token.png` },
  { symbol: 'FIL',   name: 'Filecoin',           category: 'Infrastructure', stage: 'Advanced',  description: 'Decentralised storage network — rent unused hard drive space, earn FIL.',             geckoId: 'filecoin',                    logoUrl: `${GECKO}/2682/small/file.png` },
  { symbol: 'AR',    name: 'Arweave',            category: 'Infrastructure', stage: 'Advanced',  description: 'Permanent decentralised storage — pay once, store forever on the permaweb.',          geckoId: 'arweave',                     logoUrl: `${GECKO}/4365/small/arweave.png` },
  { symbol: 'RNDR',  name: 'Render Network',     category: 'Infrastructure', stage: 'Advanced',  description: 'Decentralised GPU rendering network for AI, VFX, and metaverse content.',             geckoId: 'render-token',                logoUrl: `${GECKO}/11636/small/rndr.png` },
  { symbol: 'AKT',   name: 'Akash Network',      category: 'Infrastructure', stage: 'Advanced',  description: 'Decentralised cloud compute marketplace — AWS alternative on-chain.',                 geckoId: 'akash-network',               logoUrl: `${GECKO}/20321/small/akash-network-akt-logo.png` },
  { symbol: 'BAND',  name: 'Band Protocol',      category: 'Infrastructure', stage: 'Advanced',  description: 'Cross-chain oracle protocol — real-world data for any blockchain.',                   geckoId: 'band-protocol',               logoUrl: `${GECKO}/3843/small/band-protocol.png` },
  { symbol: 'OCEAN', name: 'Ocean Protocol',     category: 'Infrastructure', stage: 'Advanced',  description: 'Decentralised data marketplace — monetise and control your data with NFTs.',          geckoId: 'ocean-protocol',              logoUrl: `${GECKO}/3687/small/ocean-protocol-logo.jpg` },
  { symbol: 'SNX',   name: 'Synthetix',          category: 'DeFi',          stage: 'Advanced',   description: 'Derivatives liquidity protocol — synthetic assets tracking stocks, forex, and crypto.', geckoId: 'havven',                    logoUrl: `${GECKO}/3406/small/synthetix_exchange.png` },
  { symbol: 'GMX',   name: 'GMX',                category: 'DeFi',          stage: 'Advanced',   description: 'Decentralised perpetuals exchange — real yield to liquidity providers, $200M+ TVL.',  geckoId: 'gmx',                         logoUrl: `${GECKO}/18323/small/gmx-icon.png` },
  { symbol: 'DYDX',  name: 'dYdX',               category: 'DeFi',          stage: 'Advanced',   description: 'Leading on-chain perps exchange — now its own Cosmos L1 with 2,000 TPS.',            geckoId: 'dydx',                        logoUrl: `${GECKO}/17500/small/dydx.jpg` },
  { symbol: 'YFI',   name: 'Yearn Finance',      category: 'DeFi',          stage: 'Advanced',   description: 'Automated yield optimiser — aggregates DeFi strategies to maximise returns.',         geckoId: 'yearn-finance',               logoUrl: `${GECKO}/11849/small/yearn-finance.png` },
  { symbol: 'METIS', name: 'Metis',              category: 'Layer 2',       stage: 'Advanced',   description: 'Decentralised sequencer rollup — first L2 to eliminate the sequencer centralisation risk.', geckoId: 'metis-token',             logoUrl: `${GECKO}/15395/small/metis.png` },
  { symbol: 'API3',  name: 'API3',               category: 'Infrastructure', stage: 'Advanced',  description: 'First-party oracle solution — dAPIs connect smart contracts directly to API providers.', geckoId: 'api3',                      logoUrl: `${GECKO}/13930/small/api3.jpg` },
  { symbol: 'XMR',   name: 'Monero',             category: 'Privacy',        stage: 'Advanced',  description: 'Privacy-first cryptocurrency — stealth addresses, ring signatures, untraceable.',     geckoId: 'monero',                      logoUrl: `${GECKO}/69/small/monero_logo_without_background.png` },
  { symbol: 'ZEC',   name: 'Zcash',              category: 'Privacy',        stage: 'Advanced',  description: 'Zero-knowledge proofs for private transactions — shielded and transparent addresses.', geckoId: 'zcash',                       logoUrl: `${GECKO}/486/small/zcash.png` },
  { symbol: 'SCRT',  name: 'Secret Network',     category: 'Privacy',        stage: 'Advanced',  description: 'Programmable privacy L1 — encrypted smart contracts protect user data by default.',   geckoId: 'secret',                      logoUrl: `${GECKO}/11871/small/Secret_S_token.png` },
  { symbol: 'ILV',   name: 'Illuvium',           category: 'NFT/Gaming',    stage: 'Advanced',   description: 'AAA-quality open-world RPG on Ethereum — auto-battler with tradeable Illuvials.',     geckoId: 'illuvium',                    logoUrl: `${GECKO}/15322/small/ilv.jpg` },
  { symbol: 'BLUR',  name: 'Blur',               category: 'NFT/Gaming',    stage: 'Advanced',   description: 'Pro NFT marketplace and lending protocol — surpassed OpenSea in volume.',             geckoId: 'blur',                        logoUrl: `${GECKO}/28453/small/blur.png` },
  { symbol: 'GODS',  name: 'Gods Unchained',     category: 'NFT/Gaming',    stage: 'Advanced',   description: 'Competitive trading card game on Immutable X — earn real cards with real value.',     geckoId: 'gods-unchained',              logoUrl: `${GECKO}/13602/small/gods_unchained.jpeg` },
  { symbol: 'DASH',  name: 'Dash',               category: 'Payments',      stage: 'Advanced',   description: 'Instant payments network with CoinJoin privacy — pioneered masternodes and DAO governance.', geckoId: 'dash',                   logoUrl: `${GECKO}/13/small/dash_logo.png` },
];

export const STAGES: Stage[] = ['Foundation', 'Ecosystem', 'Advanced'];
