export interface LessonEntry {
  day: number;
  symbol: string;
}

export interface ConceptDay {
  day: number;
  conceptId: string;
}

export interface MonthCurriculum {
  themeSymbol: string;   // featured coin for the month hero
  tagline: string;       // short theme label
  lessons: LessonEntry[];
  quizDays: number[];
  conceptDays: ConceptDay[];
}

// Each of the 61 coins appears in exactly one month.
// Lessons are spaced ~every 5 days. Quiz days are at month-end.
// conceptDays fill in every non-lesson, non-quiz, non-Sunday weekday.
export const CURRICULUM: Record<string, MonthCurriculum> = {

  // ── Jan 2026 · Meme Season (Jan 1 = Thu, firstDayOfWeek=4) ────────────────
  '2026-01': {
    themeSymbol: 'DOGE',
    tagline: 'Meme Season',
    lessons: [
      { day: 3,  symbol: 'DOGE' },
      { day: 7,  symbol: 'SHIB' },
      { day: 12, symbol: 'PEPE' },
      { day: 16, symbol: 'BCH'  },
      { day: 21, symbol: 'LTC'  },
      { day: 26, symbol: 'DASH' },
    ],
    quizDays: [30],
    conceptDays: [
      { day: 1,  conceptId: 'blockchain-basics'    },
      { day: 2,  conceptId: 'distributed-ledger'   },
      { day: 5,  conceptId: 'cryptographic-hash'   },
      { day: 6,  conceptId: 'public-key-crypto'    },
      { day: 8,  conceptId: 'digital-signatures'   },
      { day: 9,  conceptId: 'consensus-overview'   },
      { day: 10, conceptId: 'proof-of-work'        },
      { day: 13, conceptId: 'proof-of-stake'       },
      { day: 14, conceptId: 'transaction-finality' },
      { day: 15, conceptId: 'smart-contracts'      },
      { day: 17, conceptId: 'gas-fees'             },
      { day: 19, conceptId: 'defi-overview'        },
      { day: 20, conceptId: 'nfts'                 },
      { day: 22, conceptId: 'tokenomics'           },
      { day: 23, conceptId: 'dao'                  },
      { day: 24, conceptId: 'blockchain-gaming'    },
      { day: 27, conceptId: 'oracles'              },
      { day: 28, conceptId: 'bridges'              },
      { day: 29, conceptId: 'mev'                  },
      { day: 31, conceptId: 'privacy-tech'         },
    ],
  },

  // ── Feb 2026 · Back to Basics (Feb 1 = Sun, firstDayOfWeek=0) ─────────────
  '2026-02': {
    themeSymbol: 'BTC',
    tagline: 'Back to Basics',
    lessons: [
      { day: 3,  symbol: 'BTC'  },
      { day: 8,  symbol: 'XRP'  },
      { day: 13, symbol: 'XLM'  },
      { day: 18, symbol: 'ALGO' },
      { day: 24, symbol: 'ADA'  },
    ],
    quizDays: [27],
    conceptDays: [
      { day: 2,  conceptId: 'blockchain-basics'    },
      { day: 4,  conceptId: 'distributed-ledger'   },
      { day: 5,  conceptId: 'cryptographic-hash'   },
      { day: 6,  conceptId: 'public-key-crypto'    },
      { day: 7,  conceptId: 'digital-signatures'   },
      { day: 9,  conceptId: 'consensus-overview'   },
      { day: 10, conceptId: 'proof-of-work'        },
      { day: 11, conceptId: 'proof-of-stake'       },
      { day: 12, conceptId: 'transaction-finality' },
      { day: 14, conceptId: 'smart-contracts'      },
      { day: 16, conceptId: 'gas-fees'             },
      { day: 17, conceptId: 'defi-overview'        },
      { day: 19, conceptId: 'tokenomics'           },
      { day: 20, conceptId: 'amm'                  },
      { day: 21, conceptId: 'liquidity-pools'      },
      { day: 23, conceptId: 'layer2-overview'      },
      { day: 25, conceptId: 'rollups'              },
      { day: 26, conceptId: 'oracles'              },
      { day: 28, conceptId: 'bridges'              },
    ],
  },

  // ── Mar 2026 · DeFi Summer (Mar 1 = Sun, firstDayOfWeek=0) ────────────────
  '2026-03': {
    themeSymbol: 'ETH',
    tagline: 'DeFi Summer',
    lessons: [
      { day: 3,  symbol: 'ETH'  },
      { day: 9,  symbol: 'UNI'  },
      { day: 14, symbol: 'AAVE' },
      { day: 19, symbol: 'MKR'  },
      { day: 25, symbol: 'COMP' },
    ],
    quizDays: [28],
    conceptDays: [
      { day: 2,  conceptId: 'blockchain-basics'    },
      { day: 4,  conceptId: 'defi-overview'        },
      { day: 5,  conceptId: 'smart-contracts'      },
      { day: 6,  conceptId: 'gas-fees'             },
      { day: 7,  conceptId: 'amm'                  },
      { day: 10, conceptId: 'liquidity-pools'      },
      { day: 11, conceptId: 'layer2-overview'      },
      { day: 12, conceptId: 'rollups'              },
      { day: 13, conceptId: 'zk-proofs'            },
      { day: 16, conceptId: 'oracles'              },
      { day: 17, conceptId: 'bridges'              },
      { day: 18, conceptId: 'dao'                  },
      { day: 20, conceptId: 'tokenomics'           },
      { day: 21, conceptId: 'account-abstraction'  },
      { day: 23, conceptId: 'mev'                  },
      { day: 24, conceptId: 'web3-identity'        },
      { day: 26, conceptId: 'nfts'                 },
      { day: 27, conceptId: 'blockchain-gaming'    },
      { day: 30, conceptId: 'depin'                },
      { day: 31, conceptId: 'privacy-tech'         },
    ],
  },

  // ── Apr 2026 · Speed Wars (Apr 1 = Wed, firstDayOfWeek=3) ─────────────────
  '2026-04': {
    themeSymbol: 'SOL',
    tagline: 'Speed Wars',
    lessons: [
      { day: 3,  symbol: 'SOL'  },
      { day: 8,  symbol: 'AVAX' },
      { day: 14, symbol: 'NEAR' },
      { day: 20, symbol: 'APT'  },
      { day: 26, symbol: 'SUI'  },
    ],
    quizDays: [30],
    conceptDays: [
      { day: 1,  conceptId: 'blockchain-basics'    },
      { day: 2,  conceptId: 'distributed-ledger'   },
      { day: 4,  conceptId: 'cryptographic-hash'   },
      { day: 6,  conceptId: 'consensus-overview'   },
      { day: 7,  conceptId: 'proof-of-stake'       },
      { day: 9,  conceptId: 'transaction-finality' },
      { day: 10, conceptId: 'gas-fees'             },
      { day: 11, conceptId: 'smart-contracts'      },
      { day: 13, conceptId: 'sharding'             },
      { day: 15, conceptId: 'parallel-execution'   },
      { day: 16, conceptId: 'layer2-overview'      },
      { day: 17, conceptId: 'proof-of-work'        },
      { day: 18, conceptId: 'public-key-crypto'    },
      { day: 21, conceptId: 'zk-proofs'            },
      { day: 22, conceptId: 'mev'                  },
      { day: 23, conceptId: 'tokenomics'           },
      { day: 24, conceptId: 'oracles'              },
      { day: 25, conceptId: 'bridges'              },
      { day: 27, conceptId: 'dao'                  },
      { day: 28, conceptId: 'web3-identity'        },
      { day: 29, conceptId: 'digital-signatures'   },
    ],
  },

  // ── May 2026 · The L2 Revolution (May 1 = Fri, firstDayOfWeek=5) ──────────
  '2026-05': {
    themeSymbol: 'ARB',
    tagline: 'The L2 Revolution',
    lessons: [
      { day: 4,  symbol: 'ARB'   },
      { day: 9,  symbol: 'OP'    },
      { day: 15, symbol: 'POL'   },
      { day: 21, symbol: 'STRK'  },
      { day: 27, symbol: 'METIS' },
    ],
    quizDays: [30],
    conceptDays: [
      { day: 1,  conceptId: 'layer2-overview'      },
      { day: 2,  conceptId: 'rollups'              },
      { day: 5,  conceptId: 'zk-proofs'            },
      { day: 6,  conceptId: 'sharding'             },
      { day: 7,  conceptId: 'parallel-execution'   },
      { day: 8,  conceptId: 'smart-contracts'      },
      { day: 11, conceptId: 'gas-fees'             },
      { day: 12, conceptId: 'blockchain-basics'    },
      { day: 13, conceptId: 'consensus-overview'   },
      { day: 14, conceptId: 'proof-of-stake'       },
      { day: 16, conceptId: 'account-abstraction'  },
      { day: 18, conceptId: 'bridges'              },
      { day: 19, conceptId: 'mev'                  },
      { day: 20, conceptId: 'oracles'              },
      { day: 22, conceptId: 'defi-overview'        },
      { day: 23, conceptId: 'dao'                  },
      { day: 25, conceptId: 'tokenomics'           },
      { day: 26, conceptId: 'web3-identity'        },
      { day: 28, conceptId: 'nfts'                 },
      { day: 29, conceptId: 'depin'                },
    ],
  },

  // ── Jun 2026 · The Oracle Economy (Jun 1 = Mon, firstDayOfWeek=1) ─────────
  '2026-06': {
    themeSymbol: 'LINK',
    tagline: 'The Oracle Economy',
    lessons: [
      { day: 3,  symbol: 'LINK'  },
      { day: 9,  symbol: 'GRT'   },
      { day: 15, symbol: 'BAND'  },
      { day: 21, symbol: 'API3'  },
      { day: 26, symbol: 'OCEAN' },
    ],
    quizDays: [29],
    conceptDays: [
      { day: 1,  conceptId: 'oracles'              },
      { day: 2,  conceptId: 'blockchain-basics'    },
      { day: 4,  conceptId: 'distributed-ledger'   },
      { day: 5,  conceptId: 'cryptographic-hash'   },
      { day: 6,  conceptId: 'public-key-crypto'    },
      { day: 8,  conceptId: 'consensus-overview'   },
      { day: 10, conceptId: 'defi-overview'        },
      { day: 11, conceptId: 'smart-contracts'      },
      { day: 12, conceptId: 'gas-fees'             },
      { day: 13, conceptId: 'layer2-overview'      },
      { day: 16, conceptId: 'zk-proofs'            },
      { day: 17, conceptId: 'bridges'              },
      { day: 18, conceptId: 'tokenomics'           },
      { day: 19, conceptId: 'dao'                  },
      { day: 20, conceptId: 'depin'                },
      { day: 22, conceptId: 'mev'                  },
      { day: 23, conceptId: 'account-abstraction'  },
      { day: 24, conceptId: 'web3-identity'        },
      { day: 25, conceptId: 'privacy-tech'         },
      { day: 27, conceptId: 'nfts'                 },
      { day: 28, conceptId: 'rollups'              },
      { day: 30, conceptId: 'blockchain-gaming'    },
    ],
  },

  // ── Jul 2026 · Play to Earn (Jul 1 = Wed, firstDayOfWeek=3) ──────────────
  '2026-07': {
    themeSymbol: 'AXS',
    tagline: 'Play to Earn',
    lessons: [
      { day: 3,  symbol: 'AXS'  },
      { day: 9,  symbol: 'SAND' },
      { day: 15, symbol: 'MANA' },
      { day: 21, symbol: 'GALA' },
      { day: 27, symbol: 'IMX'  },
    ],
    quizDays: [30],
    conceptDays: [
      { day: 1,  conceptId: 'blockchain-gaming'    },
      { day: 2,  conceptId: 'nfts'                 },
      { day: 4,  conceptId: 'dao'                  },
      { day: 6,  conceptId: 'tokenomics'           },
      { day: 7,  conceptId: 'smart-contracts'      },
      { day: 8,  conceptId: 'defi-overview'        },
      { day: 10, conceptId: 'blockchain-basics'    },
      { day: 11, conceptId: 'distributed-ledger'   },
      { day: 13, conceptId: 'consensus-overview'   },
      { day: 14, conceptId: 'proof-of-stake'       },
      { day: 16, conceptId: 'gas-fees'             },
      { day: 17, conceptId: 'layer2-overview'      },
      { day: 18, conceptId: 'rollups'              },
      { day: 20, conceptId: 'zk-proofs'            },
      { day: 22, conceptId: 'oracles'              },
      { day: 23, conceptId: 'bridges'              },
      { day: 24, conceptId: 'mev'                  },
      { day: 25, conceptId: 'account-abstraction'  },
      { day: 28, conceptId: 'web3-identity'        },
      { day: 29, conceptId: 'depin'                },
      { day: 31, conceptId: 'privacy-tech'         },
    ],
  },

  // ── Aug 2026 · Decentralised Cloud (Aug 1 = Sat, firstDayOfWeek=6) ────────
  '2026-08': {
    themeSymbol: 'FIL',
    tagline: 'Decentralised Cloud',
    lessons: [
      { day: 4,  symbol: 'FIL'  },
      { day: 10, symbol: 'AR'   },
      { day: 17, symbol: 'RNDR' },
      { day: 23, symbol: 'AKT'  },
      { day: 29, symbol: 'HBAR' },
    ],
    quizDays: [31],
    conceptDays: [
      { day: 1,  conceptId: 'depin'                },
      { day: 3,  conceptId: 'distributed-ledger'   },
      { day: 5,  conceptId: 'cryptographic-hash'   },
      { day: 6,  conceptId: 'public-key-crypto'    },
      { day: 7,  conceptId: 'digital-signatures'   },
      { day: 8,  conceptId: 'consensus-overview'   },
      { day: 11, conceptId: 'smart-contracts'      },
      { day: 12, conceptId: 'gas-fees'             },
      { day: 13, conceptId: 'defi-overview'        },
      { day: 14, conceptId: 'layer2-overview'      },
      { day: 15, conceptId: 'rollups'              },
      { day: 18, conceptId: 'zk-proofs'            },
      { day: 19, conceptId: 'sharding'             },
      { day: 20, conceptId: 'parallel-execution'   },
      { day: 21, conceptId: 'oracles'              },
      { day: 22, conceptId: 'bridges'              },
      { day: 24, conceptId: 'tokenomics'           },
      { day: 25, conceptId: 'dao'                  },
      { day: 26, conceptId: 'mev'                  },
      { day: 27, conceptId: 'account-abstraction'  },
      { day: 28, conceptId: 'web3-identity'        },
    ],
  },

  // ── Sep 2026 · Cross-Chain World (Sep 1 = Tue, firstDayOfWeek=2) ──────────
  '2026-09': {
    themeSymbol: 'DOT',
    tagline: 'Cross-Chain World',
    lessons: [
      { day: 3,  symbol: 'DOT'  },
      { day: 9,  symbol: 'ATOM' },
      { day: 15, symbol: 'TON'  },
      { day: 22, symbol: 'TRX'  },
      { day: 27, symbol: 'BNB'  },
    ],
    quizDays: [30],
    conceptDays: [
      { day: 1,  conceptId: 'blockchain-basics'    },
      { day: 2,  conceptId: 'bridges'              },
      { day: 4,  conceptId: 'distributed-ledger'   },
      { day: 5,  conceptId: 'cryptographic-hash'   },
      { day: 7,  conceptId: 'consensus-overview'   },
      { day: 8,  conceptId: 'proof-of-stake'       },
      { day: 10, conceptId: 'layer2-overview'      },
      { day: 11, conceptId: 'smart-contracts'      },
      { day: 12, conceptId: 'gas-fees'             },
      { day: 14, conceptId: 'defi-overview'        },
      { day: 16, conceptId: 'rollups'              },
      { day: 17, conceptId: 'zk-proofs'            },
      { day: 18, conceptId: 'sharding'             },
      { day: 19, conceptId: 'oracles'              },
      { day: 21, conceptId: 'tokenomics'           },
      { day: 23, conceptId: 'dao'                  },
      { day: 24, conceptId: 'mev'                  },
      { day: 25, conceptId: 'account-abstraction'  },
      { day: 26, conceptId: 'web3-identity'        },
      { day: 28, conceptId: 'nfts'                 },
      { day: 29, conceptId: 'depin'                },
    ],
  },

  // ── Oct 2026 · Privacy Revolution (Oct 1 = Thu, firstDayOfWeek=4) ─────────
  '2026-10': {
    themeSymbol: 'XMR',
    tagline: 'Privacy Revolution',
    lessons: [
      { day: 5,  symbol: 'XMR'  },
      { day: 11, symbol: 'ZEC'  },
      { day: 17, symbol: 'SCRT' },
      { day: 23, symbol: 'ENS'  },
      { day: 29, symbol: 'BLUR' },
    ],
    quizDays: [31],
    conceptDays: [
      { day: 1,  conceptId: 'privacy-tech'         },
      { day: 2,  conceptId: 'zk-proofs'            },
      { day: 3,  conceptId: 'cryptographic-hash'   },
      { day: 6,  conceptId: 'distributed-ledger'   },
      { day: 7,  conceptId: 'digital-signatures'   },
      { day: 8,  conceptId: 'public-key-crypto'    },
      { day: 9,  conceptId: 'consensus-overview'   },
      { day: 10, conceptId: 'proof-of-stake'       },
      { day: 12, conceptId: 'smart-contracts'      },
      { day: 13, conceptId: 'gas-fees'             },
      { day: 14, conceptId: 'defi-overview'        },
      { day: 15, conceptId: 'nfts'                 },
      { day: 16, conceptId: 'web3-identity'        },
      { day: 19, conceptId: 'blockchain-basics'    },
      { day: 20, conceptId: 'layer2-overview'      },
      { day: 21, conceptId: 'bridges'              },
      { day: 22, conceptId: 'dao'                  },
      { day: 24, conceptId: 'tokenomics'           },
      { day: 26, conceptId: 'mev'                  },
      { day: 27, conceptId: 'account-abstraction'  },
      { day: 28, conceptId: 'oracles'              },
      { day: 30, conceptId: 'depin'                },
    ],
  },

  // ── Nov 2026 · Advanced DeFi (Nov 1 = Sun, firstDayOfWeek=0) ─────────────
  '2026-11': {
    themeSymbol: 'GMX',
    tagline: 'Advanced DeFi',
    lessons: [
      { day: 4,  symbol: 'GMX'  },
      { day: 10, symbol: 'DYDX' },
      { day: 16, symbol: 'SNX'  },
      { day: 22, symbol: 'CRV'  },
      { day: 28, symbol: 'YFI'  },
    ],
    quizDays: [30],
    conceptDays: [
      { day: 2,  conceptId: 'defi-overview'        },
      { day: 3,  conceptId: 'amm'                  },
      { day: 5,  conceptId: 'liquidity-pools'      },
      { day: 6,  conceptId: 'tokenomics'           },
      { day: 7,  conceptId: 'mev'                  },
      { day: 9,  conceptId: 'smart-contracts'      },
      { day: 11, conceptId: 'gas-fees'             },
      { day: 12, conceptId: 'layer2-overview'      },
      { day: 13, conceptId: 'rollups'              },
      { day: 14, conceptId: 'zk-proofs'            },
      { day: 17, conceptId: 'oracles'              },
      { day: 18, conceptId: 'bridges'              },
      { day: 19, conceptId: 'dao'                  },
      { day: 20, conceptId: 'account-abstraction'  },
      { day: 21, conceptId: 'web3-identity'        },
      { day: 23, conceptId: 'nfts'                 },
      { day: 24, conceptId: 'depin'                },
      { day: 25, conceptId: 'privacy-tech'         },
      { day: 26, conceptId: 'blockchain-basics'    },
      { day: 27, conceptId: 'consensus-overview'   },
    ],
  },

  // ── Dec 2026 · Year in Review (Dec 1 = Tue, firstDayOfWeek=2) ─────────────
  '2026-12': {
    themeSymbol: 'RON',
    tagline: 'Year in Review',
    lessons: [
      { day: 3,  symbol: 'RON'   },
      { day: 9,  symbol: 'ILV'   },
      { day: 15, symbol: 'GODS'  },
      { day: 21, symbol: 'SUSHI' },
      { day: 27, symbol: 'LRC'   },
    ],
    quizDays: [31],
    conceptDays: [
      { day: 1,  conceptId: 'blockchain-gaming'    },
      { day: 2,  conceptId: 'nfts'                 },
      { day: 4,  conceptId: 'dao'                  },
      { day: 5,  conceptId: 'tokenomics'           },
      { day: 7,  conceptId: 'blockchain-basics'    },
      { day: 8,  conceptId: 'distributed-ledger'   },
      { day: 10, conceptId: 'smart-contracts'      },
      { day: 11, conceptId: 'gas-fees'             },
      { day: 12, conceptId: 'defi-overview'        },
      { day: 14, conceptId: 'layer2-overview'      },
      { day: 16, conceptId: 'rollups'              },
      { day: 17, conceptId: 'zk-proofs'            },
      { day: 18, conceptId: 'oracles'              },
      { day: 19, conceptId: 'bridges'              },
      { day: 22, conceptId: 'consensus-overview'   },
      { day: 23, conceptId: 'proof-of-stake'       },
      { day: 24, conceptId: 'account-abstraction'  },
      { day: 25, conceptId: 'web3-identity'        },
      { day: 26, conceptId: 'depin'                },
      { day: 28, conceptId: 'privacy-tech'         },
      { day: 29, conceptId: 'mev'                  },
      { day: 30, conceptId: 'amm'                  },
    ],
  },
};

export const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
